### ISSUE TITLE
Day 4 Issue

### ISSUE THREAD

**Issue by dileepdev7** [pi4-uiuc/Team_1#4]
My plan for today is to use the python we just learned to plot and do some basic statistical analysis on our data. 

Does anyone want to try and use R to resolve the issue David posted about our 5 different .Rmd files?

**Comment by GraceJaffe** [comment]
I'll give it a try

**Comment by dileepdev7** [comment]
As David suggested during the standup meeting, I uploaded the .ipynb file that includes all the curves on the same plot. It can be found here:

https://github.com/pi4-uiuc/Team_1/blob/data-process/basic-plotting.ipynb

**Comment by klajbor2** [comment]
@dileepdev7 this is great!

@dileepdev7 @GraceJaffe no one is assigned to this issue, you might want to do that on the right pane, you can even assign yourself

For the others in the team: this is in the data-process branch that dileep is working on. If you want to see it on your workstations, you can do:

```
git pull
git checkout data-process
```

That will switch you over to the branch `data-process`. You then have the same version of files as Dileep has been working on in that branch, including this stuff.

You can move back to the main master branch with:
```
git checkout master
```
You can always check which branch you're on with:
```
git status
```
